DROP TABLE IF EXISTS public.pollutant_meta;

CREATE TABLE public.pollutant_meta
(
    id VARCHAR(10) NOT NULL,
    parloc_ryhma_tunnus INTEGER NOT NULL,
    parloc_ryhma_nimi VARCHAR(15) NOT NULL,
    nimi VARCHAR(40) NOT NULL,
    namn VARCHAR(40) NOT NULL,
    name VARCHAR(40) NOT NULL,
    raja_arvo DOUBLE PRECISION,
    yksikko VARCHAR(15) NOT NULL,
    rap_yksikko VARCHAR(15) NOT NULL,
    ryhma VARCHAR(10),
    use_dev BOOLEAN NOT NULL DEFAULT FALSE,
    use_prod BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO
    public.pollutant_meta (id, parloc_ryhma_tunnus, parloc_ryhma_nimi, nimi, namn, name, raja_arvo, yksikko, rap_yksikko, ryhma, use_dev, use_prod)
VALUES
    ('s1', 1, 'As','Arseeni','Arseeni','Arseeni','20','kg','Mg','HM','TRUE','FALSE'),
    ('s2', 2, 'Bentseeni','Bentseeni','Bentseeni','Bentseeni','1','t','Gg',NULL,'FALSE','FALSE'),
    ('s3', 3, 'Cd','Kadmium','Kadmium','Kadmium','10','kg','Mg','HM','TRUE','FALSE'),
    ('s4', 4, 'CH4','Metaani','Metaani','Metaani','100','t','Gg','GHG','FALSE','FALSE'),
    ('s5', 5, 'CO','Hiilimonoksidi','Hiilimonoksidi','Hiilimonoksidi','500','t','Gg',NULL,'TRUE','FALSE'),
    ('s6', 6, 'CO2 (FOSS)','Hiilidioksidi, fossiilinen','Hiilidioksidi, fossiilinen','Hiilidioksidi, fossiilinen','100000','t','Gg','GHG','FALSE','FALSE'),
    ('s7', 7, 'Cr','Kromi','Kromi','Kromi','100','kg','Mg','HM','TRUE','FALSE'),
    ('s8', 8, 'Cu','Kupari','Kupari','Kupari','100','kg','Mg','HM','TRUE','FALSE'),
    ('s9', 9, 'DCM','Dikloorimetaani','Dikloorimetaani','Dikloorimetaani','1','t','Gg',NULL,'FALSE','FALSE'),
    ('s10', 10, 'Fl','Fluorit','Fluorit','Fluorit','5','t','0',NULL,'FALSE','FALSE'),
    ('s11', 11, 'HCl','Suolahappo','Suolahappo','Suolahappo','10','t','0',NULL,'FALSE','FALSE'),
    ('s12', 12, 'Hg','Elohopea','Elohopea','Elohopea','10','kg','Mg','HM','TRUE','FALSE'),
    ('s13', 13, 'NH3 + NH4','Ammoniakki','Ammoniakki','Ammoniakki','10','t','Gg',NULL,'TRUE','FALSE'),
    ('s14', 14, 'Ni','Nikkeli','Nikkeli','Nikkeli','50','kg','Mg','HM','TRUE','FALSE'),
    ('s15', 15, 'NMVOC','NMVOC','NMVOC','NMVOC','100','t','Gg',NULL,'TRUE','FALSE'),
    ('s16', 16, 'Nox','Typen oksidit','Typen oksidit','Typen oksidit','100','t','Gg',NULL,'TRUE','FALSE'),
    ('s17', 17, 'PAH-yhdisteet','PAH-yhdisteet','PAH-yhdisteet','PAH-yhdisteet','500000','g','Mg','POP','TRUE','FALSE'),
    ('s18', 18, 'Pb','Lyijy','Lyijy','Lyijy','200','kg','Mg','HM','TRUE','FALSE'),
    ('s19', 19, 'PCDD + PCDF','Dioksiinit ja furaanit','Dioksiinit ja furaanit','Dioksiinit ja furaanit','1','g','g I-Teq','POP','TRUE','FALSE'),
    ('s20', 20, 'PER','Tetrakloorietyleeni','Tetrakloorietyleeni','Tetrakloorietyleeni','2','t','Gg',NULL,'FALSE','FALSE'),
    ('s22', 22, 'SO2','Rikkidioksidi','Rikkidioksidi','Rikkidioksidi','150','t','Gg',NULL,'TRUE','FALSE'),
    ('s23', 23, 'TCE','Trikloorietaani','Trikloorietaani','Trikloorietaani','0.1','t','Gg',NULL,'FALSE','FALSE'),
    ('s24', 24, 'TRI','Trikloorietyleeni','Trikloorietyleeni','Trikloorietyleeni','2','t','Gg',NULL,'FALSE','FALSE'),
    ('s25', 25, 'Zn','Sinkki','Sinkki','Sinkki','200','kg','Mg','HM','FALSE','FALSE'),
    ('s26', 26, 'N2O','Typpioksiduuli','Typpioksiduuli','Typpioksiduuli','10','t','Gg','GHG','FALSE','FALSE'),
    ('s27', 27, 'TSP','HIUKKASET','HIUKKASET','HIUKKASET','0','t','Gg',NULL,'TRUE','FALSE'),
    ('s28', 28, 'PM 2.5','PIENHIUKKASET 2.5','PIENHIUKKASET 2.5','PIENHIUKKASET 2.5','0','t','Gg',NULL,'TRUE','FALSE'),
    ('s29', 29, 'PM 10','PIENHIUKKASET 10','PIENHIUKKASET 10','PIENHIUKKASET 10','50','t','Gg',NULL,'TRUE','FALSE'),
    ('s30', 30, 'CO2 (BIO)','Hiilidioksidi, bio','Hiilidioksidi, bio','Hiilidioksidi, bio','0','t','Gg','BIO','FALSE','FALSE'),
    ('s31', 31, 'V','Vanadiini','Vanadiini','Vanadiini','0','kg','Mg','HM','FALSE','FALSE'),
    ('s32', 32, 'Styreeni','Styreeni','Styreeni','Styreeni',NULL,'kg','kg',NULL,'FALSE','FALSE'),
    ('s34', 34, 'Nitraattityppi','Nitraattityppi','Nitraattityppi','Nitraattityppi',NULL,'kg','0',NULL,'FALSE','FALSE'),
    ('s36', 36, 'cobalt','Koboltti','Koboltti','Koboltti',NULL,'kg','Mg',NULL,'FALSE','FALSE'),
    ('s38', 38, 'HCB','Heksaklooribentseeni','Heksaklooribentseeni','Heksaklooribentseeni',NULL,'kg','kg','POP','TRUE','FALSE'),
    ('s40', 40, 'PCB','Polykloorattu bifenyyli','Polykloorattu bifenyyli','Polykloorattu bifenyyli',NULL,'g','kg','POP','TRUE','FALSE'),
    ('s41', 41, 'Mg','Mangaani','Mangaani','Mangaani',NULL,'kg','Mg',NULL,'FALSE','FALSE'),
    ('s42', 42, 'HCH','Lindaani','Lindaani','Lindaani',NULL,'g','kg','POP','FALSE','FALSE'),
    ('s43', 43, 'BC','Mustahiili','Mustahiili','Mustahiili',NULL,'t','Gg',NULL,'TRUE','FALSE'),
    ('s44', 44, 'PM 1','PIENHIUKKASET 1','PIENHIUKKASET 1','PIENHIUKKASET 1',NULL,'t','Gg',NULL,'FALSE','FALSE'),
    ('s46', 46, 'BaP','Benzo(a)pyreeni','Benzo(a)pyreeni','Benzo(a)pyreeni',NULL,'g','Mg','POP','FALSE','FALSE'),
    ('s47', 47, 'BbFA','Bentso(b)fluoranteeni','Bentso(b)fluoranteeni','Bentso(b)fluoranteeni',NULL,'g','Mg','POP','FALSE','FALSE'),
    ('s48', 48, 'BkF','Bentso(k)fluoranteeni','Bentso(k)fluoranteeni','Bentso(k)fluoranteeni',NULL,'g','Mg','POP','FALSE','FALSE'),
    ('s49', 49, 'I123cdP','Indeno(1,2,3-cd)pyreeni','Indeno(1,2,3-cd)pyreeni','Indeno(1,2,3-cd)pyreeni',NULL,'g','Mg','POP','FALSE','FALSE'),
    ('s50', 50, 'PCDD','Polyklooratut dibentso-p-dioksiinit','Polyklooratut dibentso-p-dioksiinit','Polyklooratut dibentso-p-dioksiinit',NULL,'g','g I-Teq','POP','FALSE','FALSE'),
    ('s51', 51, 'PCDF','Polyklooratut dibentsofuraanit','Polyklooratut dibentsofuraanit','Polyklooratut dibentsofuraanit',NULL,'g','g I-Teq','POP','FALSE','FALSE'),
    ('s33', 33, 'TRS','Pelkistyneet rikkiyhdisteet SO2:na','Pelkistyneet rikkiyhdisteet SO2:na','Pelkistyneet rikkiyhdisteet SO2:na',NULL,'t','Gg',NULL,'FALSE','FALSE'),
    ('s35', 35, 'Fluoridi','Fluoridi','Fluoridi','Fluoridi',NULL,'kg','0',NULL,'FALSE','FALSE'),
    ('s37', 37, 'Se','seleeni','seleeni','seleeni',NULL,'kg','Mg','HM','FALSE','FALSE'),
    ('s39', 39, 'PCP','Pentakloorifenoli','Pentakloorifenoli','Pentakloorifenoli',NULL,'kg','kg','POP','FALSE','FALSE');
